name: "qwen3_tts"
backend: "python"
max_batch_size: 32

input [
  {
    name: "text"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "language"
    data_type: TYPE_STRING
    dims: [ 1 ]
    optional: true
  },
  {
    name: "speaker"
    data_type: TYPE_STRING
    dims: [ 1 ]
    optional: true
  },
  {
    name: "streaming"
    data_type: TYPE_BOOL
    dims: [ 1 ]
    optional: true
  },
  {
    name: "end_of_text"
    data_type: TYPE_BOOL
    dims: [ 1 ]
    optional: true
  },
  {
    name: "stream_id"
    data_type: TYPE_STRING
    dims: [ 1 ]
    optional: true
  }
]

output [
  {
    name: "audio"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]

model_transaction_policy {
  decoupled: true
}

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

parameters {
  key: "vllm_model_path"
  value: { string_value: "/workspace/server/models/qwen3tts_vllm_model" }
}
parameters {
  key: "default_speaker"
  value: { string_value: "aiden" }
}
parameters {
  key: "max_tokens"
  value: { string_value: "512" }
}
parameters {
  key: "codec_chunk_size"
  value: { string_value: "30" }
}
parameters {
  key: "first_chunk_frames"
  value: { string_value: "3" }
}
parameters {
  key: "codec_left_context"
  value: { string_value: "25" }
}
parameters {
  key: "dtype"
  value: { string_value: "bfloat16" }
}
parameters {
  key: "gpu_memory_utilization"
  value: { string_value: "0.3" }
}
parameters {
  key: "max_concurrency"
  value: { string_value: "32" }
}
parameters {
  key: "text_stream_timeout_s"
  value: { string_value: "300" }
}
